### ISSUE TITLE
AdColony (4.1.3) not working on Amazon

### ISSUE THREAD

**Issue by Nomo-HSH** [AdColony/AdColony-Unity-Plugin#20]
Hi there. So it appears as though I'm encountering an almost identical [issue](https://github.com/AdColony/AdColony-Unity-Plugin/issues/5) to one reported back in version 3.3.8 of your Unity plugin.

`W/System.err: com.google.android.gms.common.GooglePlayServicesNotAvailableException
W/System.err:     at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source)
W/System.err:     at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source)
W/System.err:     at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
W/System.err:     at com.adcolony.sdk.h.a(SourceFile:329)
W/System.err:     at com.adcolony.sdk.h$b$a.run(SourceFile:1)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)`

I'm encountering this on a Kindle Fire running Fire OS 5.3.6.4
I have not encountered any issues with 4.1.3 of your plugin on an Android device with Google Play services available. Previously I had been running 3.3.11 of your Unity plugin. Any insight would be appreciated!

**Comment by Nomo-HSH** [comment]
Upon further debugging it appears that ads are showing occasionally even with this issue appearing repeatedly during an app session. I am seeing frequently failed attempts to load ads in the log output as well. I'm wondering if perhaps the Google Play Services exception occurs when an ad targeting the Google Play store is retrieved which ultimately results in an ad load failure?
