### ISSUE TITLE
How to create an issue at AdColony-Android-Plugin repository? Here is a issue

### ISSUE THREAD

**Issue by heknt** [AdColony/AdColony-Unity-Plugin#37]
Error on app initialization:

> 2022-01-28 19:31:48.928 17564-17580/com.plus1s.neya E/System: Uncaught exception thrown by finalizer
> 2022-01-28 19:31:48.931 17564-17580/com.plus1s.neya E/System: java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
>         at TM.finalize(chromium-TrichromeWebViewGoogle.apk-stable-410410681:4)
>         at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
>         at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
>         at java.lang.Daemons$Daemon.run(Daemons.java:139)
>         at java.lang.Thread.run(Thread.java:923)
>      Caused by: java.lang.Exception: AutocloseableRouter allocated at:
>         at TM.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410681:7)
>         at DP.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410681:6)
>         at org.chromium.content.browser.framehost.RenderFrameHostImpl.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410681:10)
>         at org.chromium.content.browser.framehost.RenderFrameHostImpl.create(chromium-TrichromeWebViewGoogle.apk-stable-410410681:1)
>         at J.N.MjidYpBx(Native Method)
>         at org.chromium.content.browser.webcontents.WebContentsImpl.r0(chromium-TrichromeWebViewGoogle.apk-stable-410410681:3)
>         at K7.g(chromium-TrichromeWebViewGoogle.apk-stable-410410681:5)
>         at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(chromium-TrichromeWebViewGoogle.apk-stable-410410681:4)
>         at android.webkit.WebView.postWebMessage(WebView.java:1971)
>         at com.adcolony.sdk.w0.e(SourceFile:18)
>         at com.adcolony.sdk.w0.d(SourceFile:3)
>         at com.adcolony.sdk.w0$b.onPageFinished(SourceFile:2)
>         at Fa.b(chromium-TrichromeWebViewGoogle.apk-stable-410410681:2)
>         at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:65)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7656)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Steps to reproduce:
- just follow instructions on [official android guide](https://developers.google.com/admob/android/mediation/adcolony)

**This is dublicate of** [**issue at google mediation repository**](https://github.com/googleads/googleads-mobile-android-mediation/issues/368)

**Comment by legz** [comment]
+1 the crash is still here.
